# -*- coding: utf-8 -*-
"""child_or_not.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196AVfCYWO2BCLIFnmmyNlaG-cdNxrgPW

**This is a Neural Network to Identify whether a picture is a child picture or not**
---
"""

!nvidia-smi

!pip install -Uqq fastbook

import fastbook
fastbook.setup_book()

from fastai.vision.all import *
from fastai.vision.widgets import *
from fastbook import *


from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_dir = 'gdrive/My Drive/'
base_dir = root_dir + 'Training_Photos'
path = Path(base_dir)

people = DataBlock(
    blocks=(ImageBlock, CategoryBlock),
    get_items=get_image_files,
    get_y=parent_label,
    splitter=RandomSplitter(valid_pct=0.2, seed=25)   
)

dls = people.dataloaders(path)

learn = cnn_learner(dls, resnet34  , metrics=accuracy)
learn.fine_tune(20)

corrupt = verify_images(get_image_files(path))
corrupt

dls.show_batch()

interp = ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix()
interp.plot_top_losses(10, nrows=2)

uploader = SimpleNamespace(data = ['/content/gdrive/My Drive/What.jpg'])

img = PILImage.create(uploader.data[0])

is_baby,_,probs = learn.predict(img)

print(f"{is_baby}")

learn.export('/content/gdrive/My Drive/child_or_not.pkl')
